version: "2"
services:
  
  frontend:
    container_name: frontend
    restart: always
    ports:
      - "3000:3000"
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      - REACT_APP_COUCHURL=http://localhost:35984/orders 
    depends_on:
      - couchdb
    volumes:
      - './frontend:/home/node/app'
      - '/home/node/app/node_modules'
      
  backend:
    container_name: backend
    restart: always
    environment:
      - REACT_APP_COUCHURL=http://couchdb:5984
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    links:
      - couchdb
    depends_on:
      - couchdb
    volumes:
      - './backend:/home/node/app'
      - '/home/node/app/node_modules'      
      
  couchdb:
    container_name: couchdb
    image: couchdb
    ports:
      - "35984:5984"